easy_admin:
    site_name: 'RCI Colis'
    formats:
      datetime: 'd/m/Y H:i'
    entities:
      User:
        class: App\Entity\User
        label: "Utilisateur"
        list:
          fields: [
            { property: 'username', label: "Nom d'utilisateur" }, 
            { property: 'email', label: 'Adresse email' }, 
            { property: 'lastLogin', label: 'Dernière connexion' }, 
            { property: 'enabled', label: 'Compte activé ?' }]
        edit:
          fields: [
            { property: 'username', label: "Nom d'utilisateur" }, 
            { property: 'email', label: 'Adresse email' }, 
            { property: 'lastLogin', label: 'Dernière connexion' }, 
            { property: 'enabled', label: 'Compte activé ?' }]
      #  List the entity class name you want to manage
      #  - App\Entity\Product
      #  - App\Entity\Category
      #  - App\Entity\User
