swiftmailer:
    # url: '%env(MAILER_URL)%'
    transport: smtp
    auth_mode: login
    port: 587
    host: ssl0.ovh.net
    username: ne-pas-repondre@rci-colis.com
    password: relaiscolisindependantpatricia
    spool: { type: 'memory' }